name: Slack Notification

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened]

jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          USER_LOGIN="${{ github.event.pull_request.user.login }}"
          USER_AVATAR="${{ github.event.pull_request.user.avatar_url }}"
          PR_CREATED_AT="${{ github.event.pull_request.created_at }}"
          MESSAGE="New PR opened on master:\n\n*Title:* ${PR_TITLE}\n*URL:* ${PR_URL}\n*Branch Name:* ${BRANCH_NAME}\n*Opened By:* <${USER_AVATAR}|${USER_LOGIN}>\n*Opened At:* ${PR_CREATED_AT}"
          curl -X POST -H 'Content-type: application/json' --data '{"blocks": [{"type": "section", "text": {"type": "mrkdwn", "text": "'"$MESSAGE"'"}}]}' $SLACK_WEBHOOK_URL
