name: Slack Notification

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify_slack:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          MESSAGE="New PR opened: ${{ github.event.pull_request.title }} by ${{ github.event.pull_request.user.login }}. \n\n${{ github.event.pull_request.html_url }}"
          curl -X POST -H 'Content-type: application/json' --data '{"text": "'"$MESSAGE"'"}' $SLACK_WEBHOOK_URL
